require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

target 'QMSafe' do
  pod 'RNSVG', path: '../node_modules/react-native-svg/RNSVG.podspec'

  config = use_native_modules!
   use_react_native!(:path => config["reactNativePath"])

  target 'QMSafeTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper' => '0.74.0' })
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'NO'
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end
end

target 'QMSafe-tvOS' do
  # Pods for QMSafe-tvOS

  target 'QMSafe-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
